# ----------------------------------
# ------------ 基础设置 ------------
# ----------------------------------
model_provider = "codex-for-me"
model = "gpt-5.2"
model_reasoning_effort = "xhigh"
web_search = "live" # 联网搜索：live/cached/disabled（默认 cached）

[features]
unified_exec = true
# collaboration_modes = true # Plan/Code Mode

[sandbox_workspace_write]
network_access = true # 如果在默认沙箱环境中运行，还可以允许网络访问

[model_providers.codex-for-me]
name = "codex-for-me"
base_url = "https://api-vip.codex-for.me/v1"
wire_api = "responses"
requires_openai_auth = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

# -----------------------------------
# ------------ MCP ------------------
# -----------------------------------

# auggie
[mcp_servers."augment-context-engine"]
command = "auggie"
args = ["--mcp"]

[mcp_servers."augment-context-engine".env]
AUGMENT_API_TOKEN = "ace_11b295b5d21cbe80d6067d96f8d2e7f897d228b7"
AUGMENT_API_URL = "https://acemcp.heroman.wtf/relay/"

# tavily
[mcp_servers.tavily]
command = "npx"
args = ["-y", "tavily-mcp@latest"]

[mcp_servers.tavily.env]
TAVILY_API_KEY = "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"

# context7
[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
http_headers = { "CONTEXT7_API_KEY" = "ctx7sk-e3e2d43e-0913-4712-a2ed-404ef184dba3" }


# ------------------------------------------------
# ------------ 项目信任级别设置 ------------------
# ------------------------------------------------
[projects."/home/sjj"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/OldVersion"]
trust_level = "trusted"

[projects."/home/sjj/Workspace"]
trust_level = "trusted"

[projects."/home/sjj/.codex"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/TAB"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/Main"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/Main/DataProcessor"]
trust_level = "trusted"

[projects."/home/sjj/.config/tmux"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/Main/MTSAD"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/antissh"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/Main/CutePaper"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/M2N2"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/Main/M2N2"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/New"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/MissingImputation"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AI"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/llm"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/MissingImputation/TSMI"]
trust_level = "trusted"

[projects."/home/sjj/.claude"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/LLM"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/LLM/skills"]
trust_level = "trusted"

[projects."/home/sjj/.gemini"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/Agents"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/Recipes"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/Ablation"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AnomalyDetection/Ablation/MTSAD"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/MasterThesis"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/Zotero/zotero-pdf2zh/server"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/YES"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/Lab/WireGuard"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/AD/MasterThesis"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/Test"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/Lab/DataCleaning"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/Test/AI/openspec"]
trust_level = "trusted"

[projects."/home/sjj/Workspace/codex-workflows"]
trust_level = "trusted"
